title: <p align="center"> Susmita Mishra </p>
logo: /assets/img/photo.jpg

description:
  <p align="center">
  <a href="https://github.com/sumishra-git">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning & NLP related problems.
  Currently working as Principal Software Engineer with Mnahattan Associates for last 4 years.
  Also worked on Java Microservices for 8 years with Infosys, Lowes and ADP.
  <br>
  </p>



theme: jekyll-theme-minimal
